Vagrant.configure("2") do |config|
  config.vm.box = "generic/ubuntu1804"
  config.vm.box_version = "3.2.14"

  config.ssh.insert_key = false

  # Machine specs
  config.vm.provider "libvirt" do |lv|
  end

  $script = <<-'SCRIPT'
    apt install --no-install-recommends -y \
      dwarves \
      ethtool \
      iperf3 \
      iproute2 \
      iputils-ping \
      linux-image-5.3.0-70-generic \
      linux-tools-5.3.0-70-generic \
      tcpdump \
      xxd
  SCRIPT

  config.vm.provision "shell", inline: $script
end
