# Do all VM creation in series.
# Parallel actions seem to break things.
ENV['VAGRANT_NO_PARALLEL'] = 'yes'

# Number of VMs to provision
# If N > 245, the script mus be modified
# See IP and MAC values configured below
N = 4

Vagrant.configure("2") do |config|

  (0..N-1).each do |machine_id|
    hostname = "sfc#{machine_id}"
    config.vm.define hostname do |machine|
      # See instructions on base-box dir on how to create this box
      machine.vm.box = "cb-node"
      machine.vm.hostname = hostname

      # Machine specs
      machine.vm.provider "libvirt" do |lv|
        lv.default_prefix = ""
        lv.memory = "1024"
      end

      # Configure synced folders
      machine.vm.synced_folder "../../src/", "/home/vagrant/chaining-box/src", type: "rsync", rsync__chown: true
      machine.vm.synced_folder "../../test/", "/home/vagrant/chaining-box/test", type: "rsync", rsync__chown: true
      machine.vm.synced_folder ".", "/vagrant", disabled: true

      # Fix to bug where machines are getting the same IP address.
      # Re-create machine-id file to allow correct DHCP leasing by dnsmasq
      # A `vagrant reload` is needed after this
      machine.vm.provision "shell",
        inline: "rm /etc/machine-id; systemd-machine-id-setup;"

      # A `vagrant reload` is needed after this
      machine.trigger.after :up,
        info: "Rebooting machine to get new IP...",
        run_remote: {inline: "reboot"}
    end
  end
end

# Hack to force
#system("vagrant reload")
