---
- name: Provision environment for BPF development
  hosts: all
  gather_facts: yes
  become: yes
  become_user: root
  tasks:
    - name: Install dependencies
      package:
        name:
           - patch
           - make
           - gcc
           - git
           - libssl-dev
           - bc
           - libelf-dev
           - libcap-dev
           - clang
           - gcc-multilib
           - llvm
           - libncurses5-dev
           - pkg-config
           - libmnl-dev
           - bison
           - flex
           - graphviz
           - elfutils
           - libdw-dev
           - binutils-dev
           - rsync

      tags: install

    - name: Clone linux kernel "{{ kernel_version }}" tree
      git:
        repo: https://github.com/torvalds/linux.git
        dest: "{{ kernel_dir }}"
        version: "{{ kernel_version }}"
        depth: 1 # Reduce commit history to download faster

    - name: Compile kernel headers
      shell: make headers_install INSTALL_HDR_PATH={{ install_path }}
      args:
        chdir: "{{ kernel_dir }}"
      vars:
        install_path: "{{ home }}/kernel-headers/"

    - name: Install bpftool
      shell: make && make install
      args:
        chdir: "{{ kernel_dir }}/tools/bpf/bpftool"

    - name: Install perf
      shell: make && make prefix=/usr/local install
      args:
        chdir: "{{ kernel_dir }}/tools/perf"

    - name: Clone latest iproute2
      git:
        repo: git://git.kernel.org/pub/scm/network/iproute2/iproute2.git
        dest: "{{ home }}/iproute2"
      tags: iproute2

    - name: Install latest iproute2
      shell: make && make install
      args:
        chdir: "{{ home }}/iproute2"
      tags: iproute2

    - name: Download golang
      get_url:
        url: https://dl.google.com/go/go1.13.4.linux-amd64.tar.gz
        dest: /tmp/golang.tar.gz

    - name: Install golang
      shell: tar -C /usr/local -xf golang.tar.gz && echo 'export PATH=$PATH:/usr/local/go/bin' >> ~/.profile
      args:
        chdir: /tmp

    - name: Clone libkefir
      git:
        repo: https://github.com/Netronome/libkefir.git
        dest: "{{ home }}/libkefir"
      tags: libkefir

    - name: Patch libkefir
      shell: wget -O {{ patch }} {{ url }} && patch -p1 < {{ patch }}
      args:
        chdir: "{{ home }}/libkefir"
      vars:
        url: 'https://raw.githubusercontent.com/mscastanho/chaining-box/94107a5000e6de62febe7253ef5e289d3f0b30dd/build-tools/0001-Add-function-to-fill-pinned-map.patch'
        patch: '/tmp/libkefir.patch'
      tags: libkefir

    - name: Install libkefir
      shell: make && make install install_headers
      args:
        chdir: "{{ home }}/libkefir"
      tags: libkefir
