---
# This script has been tailored for Fedora. If using it with a different distro,
# you may have to change some package names in the dependencies below.
- name: Provision environment for BPF development
  hosts: all
  gather_facts: yes
  become: yes
  become_user: root
  tasks:
    - name: Install dependencies
      package:
        name:
           - bc
           - binutils-devel
           - bison
           - bpftool
           - clang
           - dwarves
           - elfutils
           - flex
           - gcc
           - git
           - glibc-devel.i686
           - golang
           - kernel-headers
           - libbpf
           - libbpf-devel
           - libbpf-static
           - libcap-devel
           - libmnl-devel
           - llvm
           - make
           - patch
           - perf
           - pkgconf-pkg-config
           - rsync
           - wget
      tags: install

    # Install custom iproute2 to include libbpf support (included in v5.11).
    # Since that version has not been release yet, use the latest git revision.
    - name: Clone latest iproute2
      git:
        repo: https://git.kernel.org/pub/scm/network/iproute2/iproute2-next.git
        dest: "{{ home }}/iproute2"
        version: "c7897ec2a68b444b8aecc7aaeed8b80a5eefa7ea"
      tags: iproute2

    - name: Install latest iproute2
      shell: ./configure && make && make install
      args:
        chdir: "{{ home }}/iproute2"
      tags: iproute2

    - name: Clone libkefir
      git:
        repo: https://github.com/Netronome/libkefir.git
        dest: "{{ home }}/libkefir"
      tags: libkefir

    - name: Patch libkefir
      shell: wget -O {{ patch }} {{ url }} && patch -p1 < {{ patch }}
      args:
        chdir: "{{ home }}/libkefir"
      vars:
        url: 'https://raw.githubusercontent.com/mscastanho/chaining-box/94107a5000e6de62febe7253ef5e289d3f0b30dd/build-tools/0001-Add-function-to-fill-pinned-map.patch'
        patch: '/tmp/libkefir.patch'
      tags: libkefir

    - name: Install libkefir
      shell: make && make install install_headers
      args:
        chdir: "{{ home }}/libkefir"
      tags: libkefir
