Vagrant.configure("2") do |config|

  hostname = "cls" # Classifier
  config.vm.define hostname do |machine|
    machine.vm.box = "mscastanho/bpf-sandbox"
    # machine.vm.box_version = "v1.8.40"
    machine.vm.hostname = hostname

    machine.vm.network "forwarded_port",
        guest: 22,
        host: "2009"
        
    machine.ssh.insert_key = false
    machine.ssh.forward_x11 = true

    machine.vm.synced_folder "../../src/", "/home/vagrant/dsfc/src", type: "rsync", rsync__chown: true
    machine.vm.synced_folder "../../test/", "/home/vagrant/dsfc/test", type: "rsync", rsync__chown: true
    machine.vm.synced_folder ".", "/vagrant", disabled: true
    
    machine.vm.provider "libvirt" do |lv|
      lv.default_prefix = ""
      lv.memory = "1024"
      lv.graphics_type = "vnc"
      lv.graphics_ip = "0.0.0.0"
      lv.pci :bus => '0x0a', :slot => '0x00', :function => '0x0'
    end

    # Hack to change VM's XML definition since we
    # cannot add some host params through vagrant-libvirt
    config.trigger.after :up do |trigger|
      trigger.info = "Adding params to XML file"
      trigger.run = {path: "../../redefine-vm.sh", args: ["#{hostname}"]}
    end
  end

end