TARGETS += tc_bench01_redirect_kern

BUILD_DIR := ../../build

CFLAGS := -I../../headers

include ../../kernel/Makefile.in

USER_TARGETS := tc_bench01_redirect

LIBBPF_ROOT := ../../libbpf

include ../../user/Makefile.in
