#!/usr/bin/env bash

# Script to compile ChainingBox stages and userspace agents
# from the provided Docker container with all dependencies
NAME="build-$(date +%y%m%d-%H%M%S)"

# Specify user so we have the correct permissions to access
# the files generated by the build
BUILD_USER="$(id -u):$(id -g)"

docker run --name $NAME \
           --user $BUILD_USER \
		   --volume $(pwd):/cb \
		   --entrypoint "/usr/bin/make" \
		   mscastanho/chainingbox:cb-build \
		   -C /cb KDIR=/usr/src/kernel-headers-v5.3 $@
# For some reason, all arguments to the entrypoint command
# must come *after* the image name. So this last line contains
# the arguments to 'make'

# Print output
docker logs $NAME

# Remove container silently
docker rm $NAME > /dev/null
