TARGETS += flow_monitor_kern

BUILD_DIR := ../../build

CFLAGS := -I../../headers

include ../../kernel/Makefile.in

USER_TARGETS := flow_monitor

LIBBPF_ROOT := ../../libbpf

include ../../user/Makefile.in
